### ISSUE TITLE
Blank White Window

### ISSUE THREAD

**Issue by Frozen-Sherbet** [gamingdoom/datcord#21]
As of version 0.3 the application opens with a fully white window that cannot be interacted with outside of closing it. I've tried deleting .cache files as well as removing all files in .mozilla and reinstalling with no luck on resolving this. I installed via the aur and have also attempted using the tarball which both had the same problem.

**Comment by gamingdoom** [comment]
Thanks for making this issue, this bug has been fixed in version 0.3.1
