### ISSUE TITLE
Does not run on Ubuntu bionic

### ISSUE THREAD

**Issue by probonopd** [gamingdoom/datcord#3]
Does not run on bionic because it was compiled on a too new system:
> datcord: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found

Please compile on bionic or older. Thanks!

Reference:
https://github.com/AppImage/appimage.github.io/pull/2741

**Comment by gamingdoom** [comment]
Fixed in V1.2
