### ISSUE TITLE
Datcord 0.3.2 Not Starting

### ISSUE THREAD

**Issue by Cobradabest** [gamingdoom/datcord#32]
I just downloaded the new Datcord version, and it doesn't start up. I get this error in the terminal.

`/tmp/.mount_DatcorPlQbWy/AppRun: 7: Syntax error: "(" unexpected`

I'm using Ubuntu 20.4 with XFCe, if that helps.

**Comment by gamingdoom** [comment]
I am not able to reproduce this but I think that was able to find the cause of this and I have fixed it. I will be releasing a hotfix.

**Comment by gamingdoom** [comment]
Release 0.3.2 has been updated with the new version of Datcord that should fix this.

**Comment by Cobradabest** [comment]
That works, but when I try it with the argument on the terminal, I get this:

```
qt5ct: using qt5ct plugin
/tmp/.mount_DatcorGE5ONO/AppRun: 7: /home/cobradile/Applications/Datcord-x86_64_a2841776220538b5520b6a13f8441e3f.AppImage.home: Permission denied
/tmp/.mount_DatcorGE5ONO/AppRun: 13: Bad substitution
```

**Comment by gamingdoom** [comment]
I have fixed the issue with running Datcord with arguments and have updated v0.3.2's AppImage to fix it. As for the grey border, it is an intended feature to protect against browser fingerprinting called letterboxing.

**Comment by Cobradabest** [comment]
I want to turn letterboxing off, how would I do that?
