### ISSUE TITLE
Can't turn letterboxing off?

### ISSUE THREAD

**Issue by Cobradabest** [gamingdoom/datcord#33]
Hey, I've noticed the latest version of Datcord has turned on letterboxing, but I can't find any way to turn it off.

Is there any way to turn it off using about:config?

**Comment by Red1922** [comment]
`privacy.resistFingerprinting.letterboxing` = false

**Comment by gamingdoom** [comment]
So it turns out that this was a bug with mismatching code versions. I have fixed it and pushed it to Unstable. Github Actions builds broke and I am working on fixing them the builds. Once I fix those builds I will release a new version of Datcord with these fixes.
