### ISSUE TITLE
Suggestion: Add an ability to get shelter working on datcord

### ISSUE THREAD

**Issue by pipigguts** [gamingdoom/datcord#35]
It's not really an issue but I feel like it'd be a good feature, if somehow(Idk how I'm not that technical) you got Datcord to install extensions like shelter-injector on firefox extensions, or something else. Somewhat how ArmCord does it, would be really nice.

Also thank you for the work, I appreciate the firefox push against chromium monopoly.

**Comment by gamingdoom** [comment]
Hello,
I am not too sure what shelter is but, you could easily install it by opening /path/to/datcord/distribution/policies.json and changing it from
```
{
  "policies": {
    "Extensions": {
      "Install": ["https://addons.mozilla.org/firefox/downloads/file/3831723/open_with-7.2.6.xpi"]
    }
  }
}
```
to
```
{
  "policies": {
    "Extensions": {
      "Install": ["https://addons.mozilla.org/firefox/downloads/file/3831723/open_with-7.2.6.xpi", "https://addons.mozilla.org/firefox/downloads/file/4032539/shelter_injector-1.1.xpi"]
    }
  }
}
```
This works with any extension. The link is just from right-clicking the ``Add to Firefox`` and copying the link.

**Comment by pipigguts** [comment]
ohh that helps a lot ty
