### ISSUE TITLE
Title bar missing

### ISSUE THREAD

**Issue by nose-gnome** [gamingdoom/datcord#36]
Currently, the title bar is missing, meaning it is not easy to reposition Datcord.  Also, when you open a link, it opens it in another invisible tab, meaning you cannot easily go back to Discord without using keyboard shortcuts.
![image](https://user-images.githubusercontent.com/71675376/205140229-f0343ea4-d393-427c-a2e0-2f37a2c7b690.png)

**Comment by gamingdoom** [comment]
What OS are you using?

**Comment by gamingdoom** [comment]
Links opening in new tabs instead of new Datcord windows is a regression that I will fix in the next hotfix.

**Comment by nose-gnome** [comment]
System information:
OS: Ubuntu 22.10
Gnome version 43.0
Windowing System: Wayland

**Comment by gamingdoom** [comment]
Hello,
I have made quite a few changes to the backend of Datcord which might fix this issue. Please try the latest version (0.3.4) of Datcord to see if the issue persists.

**Comment by gamingdoom** [comment]
So it turns out that for Wayland, Firefox puts the window buttons inside of the tabs bar which I am hiding. I have enabled a setting for Datcord which forces a titlebar so this issue should be fixed in the next update.

**Comment by gamingdoom** [comment]
This issue should be fixed in the v0.4.0 update. Feel free to re-open if it isn't.
