### ISSUE TITLE
Generalise into a Firefox-based desktop web app library?

### ISSUE THREAD

**Issue by nclm** [gamingdoom/datcord#53]
Great to see a desktop web app using Firefox instead of Chromium!

It would be super interesting to fork this into a generalised “desktop web app kit” with relevant parameters for developers to turn any web app into a desktop client using Firefox.

Choose a name, a URL, an icon, a few other parameters, and generate your Firefox-backed app with it.

Datacord could one day be only one of many other apps based on this.

**Comment by gamingdoom** [comment]
I have actually been thinking about this idea recently, even before this issue. I will probably pursue it but no promises.

**Comment by nclm** [comment]
Good to hear!

**Comment by gamingdoom** [comment]
I have created [neutron](https://github.com/gamingdoom/neutron) which allows anyone to make an application like Datcord with just an SVG icon and at most 5 minutes going through the setup wizard.

**Comment by nclm** [comment]
Great!!
