### ISSUE TITLE
Activity does not display

### ISSUE THREAD

**Issue by PaganDegree** [gamingdoom/datcord#55]
I am not sure if this is because of Flatpak or some other reason, but my status does not update in Datcord.  So if I am playing music or a game, it does not show or reflected.  Might be a bug.  Please let me know any information you need to fix.

**Comment by gamingdoom** [comment]
This is probably impossible to fix since I would need to interact with Discord separately to send them the status info. Unless using Discord through a browser at https://discord.com/app changes your status properly then I can't fix this.
