### ISSUE TITLE
Instantly disables your discord account if you login

### ISSUE THREAD

**Issue by 32bitx64bit** [gamingdoom/datcord#56]
I've had this happen twice now.

**Comment by 32bitx64bit** [comment]
First time, got it appealed, second time just happened, and they both happened when trying to use datcord.

This is just a warning for all users, stay away from datcord, its broken.

**Comment by gamingdoom** [comment]
That's weird, I wonder how they are detecting it, it's just Firefox. Does something happen when going to https://discord.com/app on Firefox?

**Comment by gamingdoom** [comment]
If you are willing to help test, I have removed the only thing that I think could be possible to detect (the mismatching useragent). The builds are here: https://github.com/gamingdoom/datcord/actions/runs/7660187332. There is a tarball where you could just run the datcord executable once extracted.

**Comment by 32bitx64bit** [comment]
> That's weird, do you have any info on the reason? If the reason is somehow related to Datcord, I wonder how they are detecting it, it's just Firefox. Does something happen when going to https://discord.com/app on Firefox? I am not able to reproduce this. Some people on [this Reddit post](https://www.reddit.com/r/discordapp/comments/13cdkut/3_accounts_all_disabled_as_soon_i_log_in_to_them/) which has the same symptoms say that this could be an IP ban.

HI, I personally have zero idea, all I know is as soon as I log into using datcord, my account gets disabled, and I get a email saying so a couple seconds later.

I got datcord off the AUR, maybes thats the reason, all I know is I'm not risking my account again.

And the official app doesn't have issues for me. Works perfectly.

**Comment by 32bitx64bit** [comment]
I also can't really test sense... well yk. Account disabled and all.

**Comment by gamingdoom** [comment]
What version of Datcord are you using?

**Comment by 32bitx64bit** [comment]
> What version of Datcord are you using?

Was 5.0 on the releases page

**Comment by gamingdoom** [comment]
I have removed all the possible ways I could imagine that Datcord is being detected, if that's the issue, and I have also made Datcord build with a release version of Firefox, if the version of Firefox that 0.5.0 was built with had some bug causing the account to be disabled. I will be releasing these changes as 0.5.1. So, I will close this issue when that comes out. However, if anyone encounters this issue again on 0.5.1 or later, please reopen this or create a new issue.

**Comment by 32bitx64bit** [comment]
> I have removed all the possible ways I could imagine that Datcord is being detected, if that's the issue, and I have also made Datcord build with a release version of Firefox, if the version of Firefox that 0.5.0 was built with had some bug causing the account to be disabled. I will be releasing these changes as 0.5.1. So, I will close this issue when that comes out. However, if anyone encounters this issue again on 0.5.1 or later, please reopen this or create a new issue.

Alright, I've gotten my account appealed twice for this, so I probably wont be riskin. As already on thin ice.
Ima just assume fixed, closing issue. Might test on a alt when I have time.
