### ISSUE TITLE
screen sharing with audio on wayland

### ISSUE THREAD

**Issue by gmankab** [gamingdoom/datcord#59]

**Comment by gamingdoom** [comment]
Please elaborate.

**Comment by pollux56** [comment]
you can use pipewire to route the audio to the discord client, software like vesktop has venmic 
https://github.com/Vencord/venmic

**Comment by gmankab** [comment]
so, [discord-screenaudio](https://flathub.org/apps/de.shorsh.discord-screenaudio) and [vesktop](https://flathub.org/apps/dev.vencord.Vesktop) can share screen with audio on wayland

vanilla discord and datcord can't

**Comment by gamingdoom** [comment]
If you can't share audio on wayland on Firefox, than it's a Firefox bug and there is not much I can do about it.

**Comment by gmankab** [comment]
ok
