### ISSUE TITLE
[Bug] Clicked links are opened in Datcord window without a way to go back to Discord

### ISSUE THREAD

**Issue by burdoto** [gamingdoom/datcord#69]
When someone sends me a link and I click it, it opens a new tab internally inside Datcord.
There is no way for me, other than hotkeys, to go back to Discord inside Datcord.

The same applies for Firefox settings hotkeys, which happened to me the other day.

**Comment by gamingdoom** [comment]
What version are you using?

**Comment by burdoto** [comment]
OS: archlinux 6.9.4 + KDE X11
Version: 0.5.2 (AUR)

**Comment by gamingdoom** [comment]
I think you will either have to make a new profile by running datcord -P or you can follow this: https://github.com/gamingdoom/datcord/issues/60#issuecomment-2164055862

**Comment by burdoto** [comment]
Not really sure if that did something, but it seems to be working now.
It was also kind of inconsistens, sometimes it opened in Datcord, sometimes it opened in default browser already. Thanks for the advice!
